# Book Recommender System

## Importing relevant libraries

In [50]:
import numpy as np
import pandas as pd

## Loading the Datasets

In [51]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

C:\Users\nizaa\AppData\Local\Temp\ipykernel_7944\1748781244.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [52]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [53]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [54]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

## Data Preprscessing

In [55]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

## Displaying the null values in all the dataframe

In [56]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [57]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [58]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

## Discovering if there are any duplicate values

In [59]:
books.duplicated().sum()

0

In [60]:
users.duplicated().sum()

0

In [61]:
ratings.duplicated().sum()

0

# Popularity Based Recommender System

#### Here the recommendation will be done for the most popular books which will have the highest ratings
#### The number of ratings will be calulated of all only those users who have done minimum 250 ratings on any books

In [62]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [63]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'Num_Rating'},inplace=True)
num_rating_df

                                               Book-Title  Num_Rating
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.           2
241067                     Ã?Â?rger mit Produkt X. Roman.           4
241068                                Ã?Â?sterlich leben.           1
241069                              Ã?Â?stlich der Berge.           3
241070                                  Ã?Â?thique en toc           2

[241071 rows x 2 columns]

In [64]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index().round(2)
avg_rating_df.rename(columns={'Book-Rating':'Avg_Rating'},inplace=True)
avg_rating_df

C:\Users\nizaa\AppData\Local\Temp\ipykernel_7944\3877933826.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index().round(2)

                                               Book-Title  Avg_Rating
0        A Light in the Storm: The Civil War Diary of ...        2.25
1                                   Always Have Popsicles        0.00
2                    Apple Magic (The Collector's series)        0.00
3        Ask Lily (Young Women of Faith: Lily Series, ...        8.00
4        Beyond IBM: Leadership Marketing and Finance ...        0.00
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.        0.00
241067                     Ã?Â?rger mit Produkt X. Roman.        5.25
241068                                Ã?Â?sterlich leben.        7.00
241069                              Ã?Â?stlich der Berge.        2.67
241070                                  Ã?Â?thique en toc        4.00

[241071 rows x 2 columns]

In [65]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,Num_Rating,Avg_Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.25
1,Always Have Popsicles,1,0.00
2,Apple Magic (The Collector's series),1,0.00
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.00
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.00
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.00
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.25
241068,Ã?Â?sterlich leben.,1,7.00
241069,Ã?Â?stlich der Berge.,3,2.67
241070,Ã?Â?thique en toc,2,4.00

In [66]:
popular_df = popular_df[popular_df['Num_Rating']>=250].sort_values('Avg_Rating',ascending=False).head(50)

In [67]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','Num_Rating','Avg_Rating']]

In [68]:
popular_df.shape

(50, 5)

In [69]:
popular_df['Image-URL-M']

0      http://images.amazon.com/images/P/0439136350.0...
3      http://images.amazon.com/images/P/0439139597.0...
5      http://images.amazon.com/images/P/0590353403.0...
9      http://images.amazon.com/images/P/043935806X.0...
13     http://images.amazon.com/images/P/0439064872.0...
16     http://images.amazon.com/images/P/0345339681.0...
17     http://images.amazon.com/images/P/0345339703.0...
26     http://images.amazon.com/images/P/059035342X.0...
28     http://images.amazon.com/images/P/0345339711.0...
39     http://images.amazon.com/images/P/0446310786.0...
47     http://images.amazon.com/images/P/0385504209.0...
53     http://images.amazon.com/images/P/0786868716.0...
55     http://images.amazon.com/images/P/0316769487.0...
62     http://images.amazon.com/images/P/0316666343.0...
63     http://images.amazon.com/images/P/0142001740.0...
69     http://images.amazon.com/images/P/0060959037.0...
70     http://images.amazon.com/images/P/0380789019.0...
75     http://images.amazon.com/images/P/0451524934.0...
84     http://images.amazon.com/images/P/0060392452.0...
85     http://images.amazon.com/images/P/0385484518.0...
88     http://images.amazon.com/images/P/0312195516.0...
89     http://images.amazon.com/images/P/0671461494.0...
98     http://images.amazon.com/images/P/0805063897.0...
100    http://images.amazon.com/images/P/0385486804.0...
103    http://images.amazon.com/images/P/3257208626.0...
116    http://images.amazon.com/images/P/0452282152.0...
117    http://images.amazon.com/images/P/0440222915.0...
123    http://images.amazon.com/images/P/0446672211.0...
124    http://images.amazon.com/images/P/0449005615.0...
126    http://images.amazon.com/images/P/0151008116.0...
130    http://images.amazon.com/images/P/0060915544.0...
133    http://images.amazon.com/images/P/1558743669.0...
135    http://images.amazon.com/images/P/0684874350.0...
137    http://images.amazon.com/images/P/0743418174.0...
139    http://images.amazon.com/images/P/0060938455.0...
140    http://images.amazon.com/images/P/0380789035.0...
141    http://images.amazon.com/images/P/0385505833.0...
147    http://images.amazon.com/images/P/037582345X.0...
155    http://images.amazon.com/images/P/0842329129.0...
157    http://images.amazon.com/images/P/0671617028.0...
163    http://images.amazon.com/images/P/0312924585.0...
166    http://images.amazon.com/images/P/1573227331.0...
173    http://images.amazon.com/images/P/0312265840.0...
175    http://images.amazon.com/images/P/0062502174.0...
177    http://images.amazon.com/images/P/0312983867.0...
182    http://images.amazon.com/images/P/0316969443.0...
186    http://images.amazon.com/images/P/0399501487.0...
192    http://images.amazon.com/images/P/0345361792.0...
194    http://images.amazon.com/images/P/0345313860.0...
195    http://images.amazon.com/images/P/0060987103.0...
Name: Image-URL-M, dtype: object

# Collaberative Filter Based Recommender System

#### This Recommendation sytem will recommend only those books on which the minimum book Ratings are 50 and the user has rated more than 200 times

In [70]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
p_l_u = x[x].index
p_l_u

Int64Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,
              6323,   6543,
            ...
            271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427,
            277639, 278418],
           dtype='int64', name='User-ID', length=811)

In [71]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(p_l_u)]

In [72]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

In [73]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [74]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [75]:
pt.fillna(0,inplace=True)

### Importing cosine_similarity

In [76]:
from sklearn.metrics.pairwise import cosine_similarity

In [77]:
similarity_score = cosine_similarity(pt)

In [78]:
similarity_score.shape

(706, 706)

In [79]:
def recommend(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == (pt.index[i[0]])]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
        
    return data

In [80]:
recommend('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg'],
 ['The Hours : A Novel',
  'Michael Cunningham',
  'http://images.amazon.com/images/P/0312243022.01.MZZZZZZZ.jpg']]

### Importing pickle & Pickling the dataframes

In [81]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [82]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_score,open('similarity_score.pkl','wb'))